### ISSUE TITLE
MVP Updates

### ISSUE THREAD

**Issue by Franpastoragusti** [BuidlGuidl/scaffold-wallet#3]
I open this thread to collect the changes we want to make in this first iteration of the app, leave your comments below.

**Comment by Franpastoragusti** [comment]
- [X] Loading Screens
- [X] Transaction history

**Comment by ZakGriffith** [comment]
The red color arrow for outgoing transactions give me the feel that the Tx failed.  Can we adjust the color of that be more neutral?

**Comment by ZakGriffith** [comment]
When sending Eth, the confirm button gets hidden by the number pad with no clear way to either hide the buttons or confirm the tx.  Anyone have thoughts on what we can do to fix this?  Possibly move the confirm button to in between the typeable amount and the balance?

![IMG_9996](https://user-images.githubusercontent.com/12072395/209862469-b71f84ff-087a-4409-be94-e75581aaa7e3.PNG)

**Comment by Franpastoragusti** [comment]
@ZakGriffith @austintgriffith I think as a summary of things to do, reading from the channel and the issue we have that 
- [x] Red arrow icon on sent transactions feel that the Tx failed
- [x] On send eth screen keyboard hide confirm button
- [x] Loading balance behavior
- [x] Home page reorder

**Comment by ZakGriffith** [comment]
- [x] Instead of showing a 0 balance,  show that it is currently loading and display the balance only once it's properly loaded in.

**Comment by ZakGriffith** [comment]
- After switching to another account, it should redirect back to the main screen.

- The receive page will close if you click the bottom of the page, but the wallet connect page requires a downward swipe.  They should both close on a single click.  There is a nice 'close' button at the bottom of the QR scan, page.  Maybe add that button to the connect and receive pages, and add the ability to touch anywhere on the bottom to close the window.

- When selecting a different account, only the address is clickable.  Can we make that entire card be a button instead of just the characters?

- The top network selection drop down.  The arrow doesn't seem to be part of the button so clicking it doesn't do anything.  The arrow should also expand the drop down like the network name does when clicked.

- When sending Eth, the Tx appears as loading in the Transactions list.  Then it disappears entirely, then after a bit it shows up as a completed Tx.  Is there a way to keep the loading Tx visible, then switch it to a completed or failed Tx without it disappearing?

- The connect, send, and receive buttons aren't centered on an iphone 13 screen.  Screenshot included.
![IMG_0029](https://user-images.githubusercontent.com/12072395/211403776-69bc8f2b-230a-49c4-b3f8-be6c6e8fa005.PNG)
